README.md

This PR corrects the `--force_polling` command line option in README.

Correct --force_polling command line option

---

README.md

It is good to have on eyes what they are good for.
Can I add it for all other gems?

Add link and description installed gems

---

copy/all/usr/local/bin/jekyll

Thought it made sense to have drafts show up alongside future and unpublished posts in dev mode.
Thanks for a very useful image!

Makes posts from the _drafts folder show up in dev mode.

---

README.md

Documentation of how to use LiveReload feature just a link away.

Include link to http://www.rubydoc.info/gems/jekyll-reload/  in README.md

---

repos/jekyll/Dockerfile

refs #203
Print ruby version in container start up since jekyll does not do that.

print ruby version

---

repos/jekyll/Dockerfile
repos/jekyll/copy/all/usr/jekyll/bin/jekyll

hopefully print ruby version in a place visible to docker users

Print ruby version in docker

---

README.md

I try to resolve the usage documentation with docker-compose. I hope be useful.

Enhancing README

---

README.md

Update version of Jekyll in README (the title explains itself).

Update version of Jekyll in README

---

README.md

- [ x] This is a documentation change.
new creation site procedure with docker-compose

README changed creation site procedure with docker-compose

---

README.md

update of readme regarding gem caching volumes

readme update for gem caching

---

repos/jekyll/Dockerfile

This PR adds sqlite-dev that is used by libraries that uses sqlite3 ruby library.
The change should be minimal because the image already contains sqlite-lib as default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/envygeeks/jekyll-docker/271)

Add sqlite-dev

---

.travis.yml
opts.yml

Closes https://github.com/envygeeks/jekyll-docker/issues/273

Update to Jekyll 4.0.1

---

README.md

I find this helpful for remembering the correct port expose
command.

Document running the container in server mode.

---

.github/workflows/deploy.yml
.travis.yml
opts.yml

https://github.com/jekyll/jekyll/releases/tag/v4.2.2

Update to Jekyll 4.2.2

---

opts.yml
repos/jekyll/Dockerfile

Update to latest Ruby 2.x and Alpine Linux 3.x.
https://hub.docker.com/layers/ruby/library/ruby/2.7.4-alpine3.14/images/sha256-65284dcd877b7613d5ad30da974b52e59f66c047d5f827935fb8f42bb9ef6be4?context=explore

Update to Ruby 2.7.4 and Alpine Linux 3.14

---

.github/workflows/deploy.yml
README.md

Also updates the github workflow to run periodically to detect bitrot.

Replace broken travis badge

---

.dockerignore

This should speed up docker builds by reducing the context sent to the docker daemon

Added a dockerignore based on the gitignore + git

---

README.md

Add doc for JEKYLL_ROOTLESS to README

---

opts.yml

Update base image to `ruby:3.1.1-alpine3.15`.

Update to ruby:3.1.1-alpine3.15

---

README.md

These docker images are wonderful and save a lot of work. I just want to add quick start examples that would be useful to people.

Improving documentation. Adding quick start for different platforms.
